# This is a GitHub Actions pipeline file
name: Infrastructure Setup
on:
  push:
    branches: [ main ] # Triggered only after the manual approval/merge

permissions:
  id-token: write # Required for requesting the JWT from AWS
  contents: read  # Required for actions/checkout

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1 # Updated to Frankfurt

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -var="gh_token=${{ secrets.GH_TOKEN }}" -auto-approve
